using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MaterialIconsGenerator.Core;
using Newtonsoft.Json.Linq;
using RestSharp;

namespace MaterialIconsGenerator.Providers.Google
{
    public abstract class GoogleIconsProvider : IIconProvider
    {
        public string Name =>
            "Google Material Icons";

        public string Reference =>
            "https://github.com/google/material-design-icons";

        public abstract IEnumerable<ISize> GetSizes();

        public abstract IEnumerable<string> GetDensities();

        public async Task<IEnumerable<IIcon>> Get()
        {
            var json = JObject.Parse(this.GetIconsJson());

            return json["categories"].SelectMany(category =>
                category["icons"].Select(icon => new GoogleIcon()
                {
                    Id = icon["id"].Value<string>(),
                    Name = icon["id"].Value<string>(),
                    Category = new GoogleIconCategory()
                    {
                        Id = category["name"].Value<string>(),
                        Name = category["name"].Value<string>()
                    },
                    Keywords = icon["id"].Value<string>().Split(new[] { "_" }, StringSplitOptions.RemoveEmptyEntries),
                    Provider = this
                }).ToList()
            ).ToList();
        }

        public abstract IProjectIcon CreateProjectIcon(IIcon icon, IIconColor color, ISize size, string density);

        private string GetIconsJson()
        {
            return @"
{
  ""baseUrl"": ""static/icons/"",
  ""categories"": [
    {
      ""icons"": [
        { ""id"": ""ic_3d_rotation"" },
        { ""id"": ""ic_accessibility"" },
        { ""id"": ""ic_accessibility_new"" },
        { ""id"": ""ic_accessible"" },
        { ""id"": ""ic_accessible_forward"" },
        { ""id"": ""ic_account_balance"" },
        { ""id"": ""ic_account_balance_wallet"" },
        { ""id"": ""ic_account_box"" },
        { ""id"": ""ic_account_circle"" },
        { ""id"": ""ic_add_shopping_cart"" },
        { ""id"": ""ic_alarm"" },
        { ""id"": ""ic_alarm_add"" },
        { ""id"": ""ic_alarm_off"" },
        { ""id"": ""ic_alarm_on"" },
        { ""id"": ""ic_all_inbox"" },
        { ""id"": ""ic_all_out"" },
        { ""id"": ""ic_android"" },
        { ""id"": ""ic_announcement"" },
        { ""id"": ""ic_arrow_right_alt"" },
        { ""id"": ""ic_aspect_ratio"" },
        { ""id"": ""ic_assessment"" },
        { ""id"": ""ic_assignment"" },
        { ""id"": ""ic_assignment_ind"" },
        { ""id"": ""ic_assignment_late"" },
        { ""id"": ""ic_assignment_return"" },
        { ""id"": ""ic_assignment_returned"" },
        { ""id"": ""ic_assignment_turned_in"" },
        { ""id"": ""ic_autorenew"" },
        { ""id"": ""ic_backup"" },
        { ""id"": ""ic_book"" },
        { ""id"": ""ic_bookmark"" },
        { ""id"": ""ic_bookmark_border"" },
        { ""id"": ""ic_bookmarks"" },
        { ""id"": ""ic_bug_report"" },
        { ""id"": ""ic_build"" },
        { ""id"": ""ic_cached"" },
        { ""id"": ""ic_calendar_today"" },
        { ""id"": ""ic_calendar_view_day"" },
        { ""id"": ""ic_camera_enhance"" },
        { ""id"": ""ic_card_giftcard"" },
        { ""id"": ""ic_card_membership"" },
        { ""id"": ""ic_card_travel"" },
        { ""id"": ""ic_change_history"" },
        { ""id"": ""ic_check_circle"" },
        { ""id"": ""ic_check_circle_outline"" },
        { ""id"": ""ic_chrome_reader_mode"" },
        { ""id"": ""ic_class"" },
        { ""id"": ""ic_code"" },
        { ""id"": ""ic_commute"" },
        { ""id"": ""ic_compare_arrows"" },
        { ""id"": ""ic_contact_support"" },
        { ""id"": ""ic_copyright"" },
        { ""id"": ""ic_credit_card"" },
        { ""id"": ""ic_dashboard"" },
        { ""id"": ""ic_date_range"" },
        { ""id"": ""ic_delete"" },
        { ""id"": ""ic_delete_forever"" },
        { ""id"": ""ic_delete_outline"" },
        { ""id"": ""ic_description"" },
        { ""id"": ""ic_dns"" },
        { ""id"": ""ic_done"" },
        { ""id"": ""ic_done_all"" },
        { ""id"": ""ic_done_outline"" },
        { ""id"": ""ic_donut_large"" },
        { ""id"": ""ic_donut_small"" },
        { ""id"": ""ic_drag_indicator"" },
        { ""id"": ""ic_eject"" },
        { ""id"": ""ic_euro_symbol"" },
        { ""id"": ""ic_event"" },
        { ""id"": ""ic_event_seat"" },
        { ""id"": ""ic_exit_to_app"" },
        { ""id"": ""ic_explore"" },
        { ""id"": ""ic_explore_off"" },
        { ""id"": ""ic_extension"" },
        { ""id"": ""ic_face"" },
        { ""id"": ""ic_favorite"" },
        { ""id"": ""ic_favorite_border"" },
        { ""id"": ""ic_feedback"" },
        { ""id"": ""ic_find_in_page"" },
        { ""id"": ""ic_find_replace"" },
        { ""id"": ""ic_fingerprint"" },
        { ""id"": ""ic_flight_land"" },
        { ""id"": ""ic_flight_takeoff"" },
        { ""id"": ""ic_flip_to_back"" },
        { ""id"": ""ic_flip_to_front"" },
        { ""id"": ""ic_g_translate"" },
        { ""id"": ""ic_gavel"" },
        { ""id"": ""ic_get_app"" },
        { ""id"": ""ic_gif"" },
        { ""id"": ""ic_grade"" },
        { ""id"": ""ic_group_work"" },
        { ""id"": ""ic_help"" },
        { ""id"": ""ic_help_outline"" },
        { ""id"": ""ic_highlight_off"" },
        { ""id"": ""ic_history"" },
        { ""id"": ""ic_home"" },
        { ""id"": ""ic_horizontal_split"" },
        { ""id"": ""ic_hourglass_empty"" },
        { ""id"": ""ic_hourglass_full"" },
        { ""id"": ""ic_http"" },
        { ""id"": ""ic_https"" },
        { ""id"": ""ic_important_devices"" },
        { ""id"": ""ic_info"" },
        { ""id"": ""ic_input"" },
        { ""id"": ""ic_invert_colors"" },
        { ""id"": ""ic_label"" },
        { ""id"": ""ic_label_important"" },
        { ""id"": ""ic_label_off"" },
        { ""id"": ""ic_language"" },
        { ""id"": ""ic_launch"" },
        { ""id"": ""ic_line_style"" },
        { ""id"": ""ic_line_weight"" },
        { ""id"": ""ic_list"" },
        { ""id"": ""ic_lock"" },
        { ""id"": ""ic_lock_open"" },
        { ""id"": ""ic_loyalty"" },
        { ""id"": ""ic_markunread_mailbox"" },
        { ""id"": ""ic_maximize"" },
        { ""id"": ""ic_minimize"" },
        { ""id"": ""ic_motorcycle"" },
        { ""id"": ""ic_note_add"" },
        { ""id"": ""ic_offline_bolt"" },
        { ""id"": ""ic_offline_pin"" },
        { ""id"": ""ic_opacity"" },
        { ""id"": ""ic_open_in_browser"" },
        { ""id"": ""ic_open_in_new"" },
        { ""id"": ""ic_open_with"" },
        { ""id"": ""ic_pageview"" },
        { ""id"": ""ic_pan_tool"" },
        { ""id"": ""ic_payment"" },
        { ""id"": ""ic_perm_camera_mic"" },
        { ""id"": ""ic_perm_contact_calendar"" },
        { ""id"": ""ic_perm_data_setting"" },
        { ""id"": ""ic_perm_device_information"" },
        { ""id"": ""ic_perm_identity"" },
        { ""id"": ""ic_perm_media"" },
        { ""id"": ""ic_perm_phone_msg"" },
        { ""id"": ""ic_perm_scan_wifi"" },
        { ""id"": ""ic_pets"" },
        { ""id"": ""ic_picture_in_picture"" },
        { ""id"": ""ic_picture_in_picture_alt"" },
        { ""id"": ""ic_play_for_work"" },
        { ""id"": ""ic_polymer"" },
        { ""id"": ""ic_power_settings_new"" },
        { ""id"": ""ic_pregnant_woman"" },
        { ""id"": ""ic_print"" },
        { ""id"": ""ic_query_builder"" },
        { ""id"": ""ic_question_answer"" },
        { ""id"": ""ic_receipt"" },
        { ""id"": ""ic_record_voice_over"" },
        { ""id"": ""ic_redeem"" },
        { ""id"": ""ic_remove_shopping_cart"" },
        { ""id"": ""ic_reorder"" },
        { ""id"": ""ic_report_problem"" },
        { ""id"": ""ic_restore"" },
        { ""id"": ""ic_restore_from_trash"" },
        { ""id"": ""ic_restore_page"" },
        { ""id"": ""ic_room"" },
        { ""id"": ""ic_rounded_corner"" },
        { ""id"": ""ic_rowing"" },
        { ""id"": ""ic_schedule"" },
        { ""id"": ""ic_search"" },
        {
          ""imageUrls"": {
            ""twotone"": ""twotone-settings-24px.svg"",
            ""sharp"": ""sharp-settings-24px.svg"",
            ""outline"": ""outline-settings-24px.svg"",
            ""round"": ""round-settings-24px.svg"",
            ""baseline"": ""baseline-settings-20px.svg""
          },
          ""id"": ""ic_settings""
        },
        { ""id"": ""ic_settings_applications"" },
        { ""id"": ""ic_settings_backup_restore"" },
        { ""id"": ""ic_settings_bluetooth"" },
        { ""id"": ""ic_settings_brightness"" },
        { ""id"": ""ic_settings_cell"" },
        { ""id"": ""ic_settings_ethernet"" },
        { ""id"": ""ic_settings_input_antenna"" },
        { ""id"": ""ic_settings_input_component"" },
        { ""id"": ""ic_settings_input_composite"" },
        { ""id"": ""ic_settings_input_hdmi"" },
        { ""id"": ""ic_settings_input_svideo"" },
        { ""id"": ""ic_settings_overscan"" },
        { ""id"": ""ic_settings_phone"" },
        { ""id"": ""ic_settings_power"" },
        { ""id"": ""ic_settings_remote"" },
        { ""id"": ""ic_settings_voice"" },
        { ""id"": ""ic_shop"" },
        { ""id"": ""ic_shop_two"" },
        { ""id"": ""ic_shopping_basket"" },
        { ""id"": ""ic_shopping_cart"" },
        { ""id"": ""ic_speaker_notes"" },
        { ""id"": ""ic_speaker_notes_off"" },
        { ""id"": ""ic_spellcheck"" },
        {
          ""imageUrls"": {
            ""twotone"": ""twotone-star_rate-18px.svg"",
            ""sharp"": ""sharp-star_rate-18px.svg"",
            ""outline"": ""outline-star_rate-18px.svg"",
            ""round"": ""round-star_rate-18px.svg"",
            ""baseline"": ""baseline-star_rate-18px.svg""
          },
          ""id"": ""ic_star_rate""
        },
        { ""id"": ""ic_stars"" },
        { ""id"": ""ic_store"" },
        { ""id"": ""ic_subject"" },
        { ""id"": ""ic_supervised_user_circle"" },
        { ""id"": ""ic_supervisor_account"" },
        { ""id"": ""ic_swap_horiz"" },
        { ""id"": ""ic_swap_horizontal_circle"" },
        { ""id"": ""ic_swap_vert"" },
        { ""id"": ""ic_swap_vertical_circle"" },
        { ""id"": ""ic_tab"" },
        { ""id"": ""ic_tab_unselected"" },
        { ""id"": ""ic_text_rotate_up"" },
        { ""id"": ""ic_text_rotate_vertical"" },
        { ""id"": ""ic_text_rotation_down"" },
        { ""id"": ""ic_text_rotation_none"" },
        { ""id"": ""ic_theaters"" },
        { ""id"": ""ic_thumb_down"" },
        { ""id"": ""ic_thumb_up"" },
        { ""id"": ""ic_thumbs_up_down"" },
        { ""id"": ""ic_timeline"" },
        { ""id"": ""ic_toc"" },
        { ""id"": ""ic_today"" },
        { ""id"": ""ic_toll"" },
        { ""id"": ""ic_touch_app"" },
        { ""id"": ""ic_track_changes"" },
        { ""id"": ""ic_translate"" },
        { ""id"": ""ic_trending_down"" },
        { ""id"": ""ic_trending_flat"" },
        { ""id"": ""ic_trending_up"" },
        { ""id"": ""ic_turned_in"" },
        { ""id"": ""ic_turned_in_not"" },
        { ""id"": ""ic_update"" },
        { ""id"": ""ic_verified_user"" },
        { ""id"": ""ic_vertical_split"" },
        { ""id"": ""ic_view_agenda"" },
        { ""id"": ""ic_view_array"" },
        { ""id"": ""ic_view_carousel"" },
        { ""id"": ""ic_view_column"" },
        { ""id"": ""ic_view_day"" },
        { ""id"": ""ic_view_headline"" },
        { ""id"": ""ic_view_list"" },
        { ""id"": ""ic_view_module"" },
        { ""id"": ""ic_view_quilt"" },
        { ""id"": ""ic_view_stream"" },
        { ""id"": ""ic_view_week"" },
        { ""id"": ""ic_visibility"" },
        { ""id"": ""ic_visibility_off"" },
        { ""id"": ""ic_voice_over_off"" },
        { ""id"": ""ic_watch_later"" },
        { ""id"": ""ic_work"" },
        { ""id"": ""ic_work_off"" },
        { ""id"": ""ic_work_outline"" },
        { ""id"": ""ic_youtube_searched_for"" },
        { ""id"": ""ic_zoom_in"" },
        { ""id"": ""ic_zoom_out"" }
      ],
      ""name"": ""action""
    },
    {
      ""icons"": [
        { ""id"": ""ic_add_alert"" },
        { ""id"": ""ic_error"" },
        { ""id"": ""ic_error_outline"" },
        { ""id"": ""ic_notification_important"" },
        { ""id"": ""ic_warning"" }
      ],
      ""name"": ""alert""
    },
    {
      ""icons"": [
        { ""id"": ""ic_4k"" },
        { ""id"": ""ic_add_to_queue"" },
        { ""id"": ""ic_airplay"" },
        { ""id"": ""ic_album"" },
        { ""id"": ""ic_art_track"" },
        { ""id"": ""ic_av_timer"" },
        { ""id"": ""ic_branding_watermark"" },
        { ""id"": ""ic_call_to_action"" },
        { ""id"": ""ic_closed_caption"" },
        { ""id"": ""ic_control_camera"" },
        { ""id"": ""ic_equalizer"" },
        { ""id"": ""ic_explicit"" },
        { ""id"": ""ic_fast_forward"" },
        { ""id"": ""ic_fast_rewind"" },
        { ""id"": ""ic_featured_play_list"" },
        { ""id"": ""ic_featured_video"" },
        { ""id"": ""ic_fiber_dvr"" },
        { ""id"": ""ic_fiber_manual_record"" },
        { ""id"": ""ic_fiber_new"" },
        { ""id"": ""ic_fiber_pin"" },
        { ""id"": ""ic_fiber_smart_record"" },
        { ""id"": ""ic_forward_10"" },
        { ""id"": ""ic_forward_30"" },
        { ""id"": ""ic_forward_5"" },
        { ""id"": ""ic_games"" },
        { ""id"": ""ic_hd"" },
        { ""id"": ""ic_hearing"" },
        { ""id"": ""ic_high_quality"" },
        { ""id"": ""ic_library_add"" },
        { ""id"": ""ic_library_books"" },
        { ""id"": ""ic_library_music"" },
        { ""id"": ""ic_loop"" },
        { ""id"": ""ic_mic"" },
        { ""id"": ""ic_mic_none"" },
        { ""id"": ""ic_mic_off"" },
        { ""id"": ""ic_missed_video_call"" },
        { ""id"": ""ic_movie"" },
        { ""id"": ""ic_music_video"" },
        { ""id"": ""ic_new_releases"" },
        { ""id"": ""ic_not_interested"" },
        { ""id"": ""ic_note"" },
        { ""id"": ""ic_pause"" },
        { ""id"": ""ic_pause_circle_filled"" },
        { ""id"": ""ic_pause_circle_outline"" },
        { ""id"": ""ic_play_arrow"" },
        { ""id"": ""ic_play_circle_filled"" },
        {
          ""imageUrls"": {
            ""twotone"": ""twotone-play_circle_filled_white-24px.svg"",
            ""sharp"": ""sharp-play_circle_filled_white-24px.svg"",
            ""outline"": ""outline-play_circle_filled_white-24px.svg"",
            ""round"": ""round-play_circle_filled_white-24px.svg"",
            ""baseline"": ""baseline-play_circle_filled_white-48px.svg""
          },
          ""id"": ""ic_play_circle_filled_white""
        },
        { ""id"": ""ic_play_circle_outline"" },
        { ""id"": ""ic_playlist_add"" },
        { ""id"": ""ic_playlist_add_check"" },
        { ""id"": ""ic_playlist_play"" },
        { ""id"": ""ic_queue"" },
        { ""id"": ""ic_queue_music"" },
        { ""id"": ""ic_queue_play_next"" },
        { ""id"": ""ic_radio"" },
        { ""id"": ""ic_recent_actors"" },
        { ""id"": ""ic_remove_from_queue"" },
        { ""id"": ""ic_repeat"" },
        { ""id"": ""ic_repeat_one"" },
        { ""id"": ""ic_replay"" },
        { ""id"": ""ic_replay_10"" },
        { ""id"": ""ic_replay_30"" },
        { ""id"": ""ic_replay_5"" },
        { ""id"": ""ic_shuffle"" },
        { ""id"": ""ic_skip_next"" },
        { ""id"": ""ic_skip_previous"" },
        { ""id"": ""ic_slow_motion_video"" },
        { ""id"": ""ic_snooze"" },
        { ""id"": ""ic_sort_by_alpha"" },
        { ""id"": ""ic_stop"" },
        { ""id"": ""ic_subscriptions"" },
        { ""id"": ""ic_subtitles"" },
        { ""id"": ""ic_surround_sound"" },
        { ""id"": ""ic_video_call"" },
        { ""id"": ""ic_video_label"" },
        { ""id"": ""ic_video_library"" },
        { ""id"": ""ic_videocam"" },
        { ""id"": ""ic_videocam_off"" },
        { ""id"": ""ic_volume_down"" },
        { ""id"": ""ic_volume_mute"" },
        { ""id"": ""ic_volume_off"" },
        { ""id"": ""ic_volume_up"" },
        { ""id"": ""ic_web"" },
        { ""id"": ""ic_web_asset"" }
      ],
      ""name"": ""av""
    },
    {
      ""icons"": [
        { ""id"": ""ic_alternate_email"" },
        { ""id"": ""ic_business"" },
        { ""id"": ""ic_call"" },
        { ""id"": ""ic_call_end"" },
        { ""id"": ""ic_call_made"" },
        { ""id"": ""ic_call_merge"" },
        { ""id"": ""ic_call_missed"" },
        { ""id"": ""ic_call_missed_outgoing"" },
        { ""id"": ""ic_call_received"" },
        { ""id"": ""ic_call_split"" },
        { ""id"": ""ic_cancel_presentation"" },
        { ""id"": ""ic_cell_wifi"" },
        { ""id"": ""ic_chat"" },
        { ""id"": ""ic_chat_bubble"" },
        { ""id"": ""ic_chat_bubble_outline"" },
        { ""id"": ""ic_clear_all"" },
        { ""id"": ""ic_comment"" },
        { ""id"": ""ic_contact_mail"" },
        { ""id"": ""ic_contact_phone"" },
        { ""id"": ""ic_contacts"" },
        { ""id"": ""ic_desktop_access_disabled"" },
        { ""id"": ""ic_dialer_sip"" },
        { ""id"": ""ic_dialpad"" },
        { ""id"": ""ic_domain_disabled"" },
        { ""id"": ""ic_duo"" },
        { ""id"": ""ic_email"" },
        { ""id"": ""ic_forum"" },
        { ""id"": ""ic_import_contacts"" },
        { ""id"": ""ic_import_export"" },
        { ""id"": ""ic_invert_colors_off"" },
        { ""id"": ""ic_list_alt"" },
        { ""id"": ""ic_live_help"" },
        { ""id"": ""ic_location_off"" },
        { ""id"": ""ic_location_on"" },
        { ""id"": ""ic_mail_outline"" },
        { ""id"": ""ic_message"" },
        { ""id"": ""ic_mobile_screen_share"" },
        { ""id"": ""ic_no_sim"" },
        { ""id"": ""ic_pause_presentation"" },
        { ""id"": ""ic_person_add_disabled"" },
        { ""id"": ""ic_phone"" },
        { ""id"": ""ic_phonelink_erase"" },
        { ""id"": ""ic_phonelink_lock"" },
        { ""id"": ""ic_phonelink_ring"" },
        { ""id"": ""ic_phonelink_setup"" },
        { ""id"": ""ic_portable_wifi_off"" },
        { ""id"": ""ic_present_to_all"" },
        { ""id"": ""ic_print_disabled"" },
        { ""id"": ""ic_ring_volume"" },
        { ""id"": ""ic_rss_feed"" },
        { ""id"": ""ic_screen_share"" },
        { ""id"": ""ic_sentiment_satisfied_alt"" },
        { ""id"": ""ic_speaker_phone"" },
        { ""id"": ""ic_stay_current_landscape"" },
        { ""id"": ""ic_stay_current_portrait"" },
        { ""id"": ""ic_stay_primary_landscape"" },
        { ""id"": ""ic_stay_primary_portrait"" },
        { ""id"": ""ic_stop_screen_share"" },
        { ""id"": ""ic_swap_calls"" },
        { ""id"": ""ic_textsms"" },
        { ""id"": ""ic_unsubscribe"" },
        { ""id"": ""ic_voicemail"" },
        { ""id"": ""ic_vpn_key"" }
      ],
      ""name"": ""communication""
    },
    {
      ""icons"": [
        { ""id"": ""ic_add"" },
        { ""id"": ""ic_add_box"" },
        { ""id"": ""ic_add_circle"" },
        { ""id"": ""ic_add_circle_outline"" },
        { ""id"": ""ic_archive"" },
        { ""id"": ""ic_backspace"" },
        { ""id"": ""ic_ballot"" },
        { ""id"": ""ic_block"" },
        { ""id"": ""ic_clear"" },
        { ""id"": ""ic_create"" },
        { ""id"": ""ic_delete_sweep"" },
        { ""id"": ""ic_drafts"" },
        { ""id"": ""ic_file_copy"" },
        { ""id"": ""ic_filter_list"" },
        { ""id"": ""ic_flag"" },
        { ""id"": ""ic_font_download"" },
        { ""id"": ""ic_forward"" },
        { ""id"": ""ic_gesture"" },
        { ""id"": ""ic_how_to_reg"" },
        { ""id"": ""ic_how_to_vote"" },
        { ""id"": ""ic_inbox"" },
        { ""id"": ""ic_link"" },
        { ""id"": ""ic_link_off"" },
        { ""id"": ""ic_low_priority"" },
        { ""id"": ""ic_mail"" },
        { ""id"": ""ic_markunread"" },
        { ""id"": ""ic_move_to_inbox"" },
        { ""id"": ""ic_next_week"" },
        { ""id"": ""ic_outlined_flag"" },
        { ""id"": ""ic_redo"" },
        { ""id"": ""ic_remove"" },
        { ""id"": ""ic_remove_circle"" },
        { ""id"": ""ic_remove_circle_outline"" },
        { ""id"": ""ic_reply"" },
        { ""id"": ""ic_reply_all"" },
        { ""id"": ""ic_report"" },
        { ""id"": ""ic_report_off"" },
        { ""id"": ""ic_save"" },
        { ""id"": ""ic_save_alt"" },
        { ""id"": ""ic_select_all"" },
        { ""id"": ""ic_send"" },
        { ""id"": ""ic_sort"" },
        { ""id"": ""ic_text_format"" },
        { ""id"": ""ic_unarchive"" },
        { ""id"": ""ic_undo"" },
        { ""id"": ""ic_waves"" },
        {
          ""imageUrls"": {
            ""twotone"": ""twotone-weekend-24px.svg"",
            ""sharp"": ""sharp-weekend-24px.svg"",
            ""outline"": ""outline-weekend-24px.svg"",
            ""round"": ""round-weekend-24px.svg"",
            ""baseline"": ""baseline-weekend-48px.svg""
          },
          ""id"": ""ic_weekend""
        },
        { ""id"": ""ic_where_to_vote"" }
      ],
      ""name"": ""content""
    },
    {
      ""icons"": [
        { ""id"": ""ic_access_alarm"" },
        { ""id"": ""ic_access_alarms"" },
        { ""id"": ""ic_access_time"" },
        { ""id"": ""ic_add_alarm"" },
        { ""id"": ""ic_add_to_home_screen"" },
        { ""id"": ""ic_airplanemode_active"" },
        { ""id"": ""ic_airplanemode_inactive"" },
        { ""id"": ""ic_battery_20"" },
        { ""id"": ""ic_battery_30"" },
        { ""id"": ""ic_battery_50"" },
        { ""id"": ""ic_battery_60"" },
        { ""id"": ""ic_battery_80"" },
        { ""id"": ""ic_battery_90"" },
        { ""id"": ""ic_battery_alert"" },
        { ""id"": ""ic_battery_charging_20"" },
        { ""id"": ""ic_battery_charging_30"" },
        { ""id"": ""ic_battery_charging_50"" },
        { ""id"": ""ic_battery_charging_60"" },
        { ""id"": ""ic_battery_charging_80"" },
        { ""id"": ""ic_battery_charging_90"" },
        { ""id"": ""ic_battery_charging_full"" },
        { ""id"": ""ic_battery_full"" },
        { ""id"": ""ic_battery_std"" },
        { ""id"": ""ic_battery_unknown"" },
        { ""id"": ""ic_bluetooth"" },
        { ""id"": ""ic_bluetooth_connected"" },
        { ""id"": ""ic_bluetooth_disabled"" },
        { ""id"": ""ic_bluetooth_searching"" },
        { ""id"": ""ic_brightness_auto"" },
        { ""id"": ""ic_brightness_high"" },
        { ""id"": ""ic_brightness_low"" },
        { ""id"": ""ic_brightness_medium"" },
        { ""id"": ""ic_data_usage"" },
        { ""id"": ""ic_developer_mode"" },
        { ""id"": ""ic_devices"" },
        { ""id"": ""ic_dvr"" },
        { ""id"": ""ic_gps_fixed"" },
        { ""id"": ""ic_gps_not_fixed"" },
        { ""id"": ""ic_gps_off"" },
        { ""id"": ""ic_graphic_eq"" },
        { ""id"": ""ic_location_disabled"" },
        { ""id"": ""ic_location_searching"" },
        { ""id"": ""ic_mobile_friendly"" },
        { ""id"": ""ic_mobile_off"" },
        { ""id"": ""ic_network_cell"" },
        { ""id"": ""ic_network_wifi"" },
        { ""id"": ""ic_nfc"" },
        { ""id"": ""ic_screen_lock_landscape"" },
        { ""id"": ""ic_screen_lock_portrait"" },
        { ""id"": ""ic_screen_lock_rotation"" },
        { ""id"": ""ic_screen_rotation"" },
        { ""id"": ""ic_sd_storage"" },
        { ""id"": ""ic_settings_system_daydream"" },
        { ""id"": ""ic_signal_cellular_0_bar"" },
        { ""id"": ""ic_signal_cellular_1_bar"" },
        { ""id"": ""ic_signal_cellular_2_bar"" },
        { ""id"": ""ic_signal_cellular_3_bar"" },
        { ""id"": ""ic_signal_cellular_4_bar"" },
        { ""id"": ""ic_signal_cellular_alt"" },
        { ""id"": ""ic_signal_cellular_connected_no_internet_0_bar"" },
        { ""id"": ""ic_signal_cellular_connected_no_internet_1_bar"" },
        { ""id"": ""ic_signal_cellular_connected_no_internet_2_bar"" },
        { ""id"": ""ic_signal_cellular_connected_no_internet_3_bar"" },
        { ""id"": ""ic_signal_cellular_connected_no_internet_4_bar"" },
        { ""id"": ""ic_signal_cellular_no_sim"" },
        { ""id"": ""ic_signal_cellular_null"" },
        { ""id"": ""ic_signal_cellular_off"" },
        { ""id"": ""ic_signal_wifi_0_bar"" },
        { ""id"": ""ic_signal_wifi_1_bar"" },
        { ""id"": ""ic_signal_wifi_1_bar_lock"" },
        { ""id"": ""ic_signal_wifi_2_bar"" },
        { ""id"": ""ic_signal_wifi_2_bar_lock"" },
        { ""id"": ""ic_signal_wifi_3_bar"" },
        { ""id"": ""ic_signal_wifi_3_bar_lock"" },
        { ""id"": ""ic_signal_wifi_4_bar"" },
        { ""id"": ""ic_signal_wifi_4_bar_lock"" },
        { ""id"": ""ic_signal_wifi_off"" },
        { ""id"": ""ic_storage"" },
        { ""id"": ""ic_usb"" },
        { ""id"": ""ic_wallpaper"" },
        { ""id"": ""ic_widgets"" },
        { ""id"": ""ic_wifi_lock"" },
        { ""id"": ""ic_wifi_tethering"" }
      ],
      ""name"": ""device""
    },
    {
      ""icons"": [
        { ""id"": ""ic_add_comment"" },
        { ""id"": ""ic_attach_file"" },
        { ""id"": ""ic_attach_money"" },
        { ""id"": ""ic_bar_chart"" },
        { ""id"": ""ic_border_all"" },
        { ""id"": ""ic_border_bottom"" },
        { ""id"": ""ic_border_clear"" },
        { ""id"": ""ic_border_color"" },
        { ""id"": ""ic_border_horizontal"" },
        { ""id"": ""ic_border_inner"" },
        { ""id"": ""ic_border_left"" },
        { ""id"": ""ic_border_outer"" },
        { ""id"": ""ic_border_right"" },
        { ""id"": ""ic_border_style"" },
        { ""id"": ""ic_border_top"" },
        { ""id"": ""ic_border_vertical"" },
        { ""id"": ""ic_bubble_chart"" },
        { ""id"": ""ic_drag_handle"" },
        { ""id"": ""ic_format_align_center"" },
        { ""id"": ""ic_format_align_justify"" },
        { ""id"": ""ic_format_align_left"" },
        { ""id"": ""ic_format_align_right"" },
        { ""id"": ""ic_format_bold"" },
        { ""id"": ""ic_format_clear"" },
        { ""id"": ""ic_format_color_fill"" },
        { ""id"": ""ic_format_color_reset"" },
        { ""id"": ""ic_format_color_text"" },
        { ""id"": ""ic_format_indent_decrease"" },
        { ""id"": ""ic_format_indent_increase"" },
        { ""id"": ""ic_format_italic"" },
        { ""id"": ""ic_format_line_spacing"" },
        { ""id"": ""ic_format_list_bulleted"" },
        { ""id"": ""ic_format_list_numbered"" },
        { ""id"": ""ic_format_list_numbered_rtl"" },
        { ""id"": ""ic_format_paint"" },
        { ""id"": ""ic_format_quote"" },
        { ""id"": ""ic_format_shapes"" },
        { ""id"": ""ic_format_size"" },
        { ""id"": ""ic_format_strikethrough"" },
        { ""id"": ""ic_format_textdirection_l_to_r"" },
        { ""id"": ""ic_format_textdirection_r_to_l"" },
        { ""id"": ""ic_format_underlined"" },
        { ""id"": ""ic_functions"" },
        { ""id"": ""ic_highlight"" },
        { ""id"": ""ic_insert_chart"" },
        { ""id"": ""ic_insert_chart_outlined"" },
        { ""id"": ""ic_insert_comment"" },
        { ""id"": ""ic_insert_drive_file"" },
        { ""id"": ""ic_insert_emoticon"" },
        { ""id"": ""ic_insert_invitation"" },
        { ""id"": ""ic_insert_link"" },
        { ""id"": ""ic_insert_photo"" },
        { ""id"": ""ic_linear_scale"" },
        { ""id"": ""ic_merge_type"" },
        { ""id"": ""ic_mode_comment"" },
        { ""id"": ""ic_monetization_on"" },
        { ""id"": ""ic_money_off"" },
        { ""id"": ""ic_multiline_chart"" },
        { ""id"": ""ic_notes"" },
        { ""id"": ""ic_pie_chart"" },
        { ""id"": ""ic_publish"" },
        { ""id"": ""ic_scatter_plot"" },
        { ""id"": ""ic_score"" },
        { ""id"": ""ic_short_text"" },
        { ""id"": ""ic_show_chart"" },
        { ""id"": ""ic_space_bar"" },
        { ""id"": ""ic_strikethrough_s"" },
        { ""id"": ""ic_table_chart"" },
        { ""id"": ""ic_text_fields"" },
        { ""id"": ""ic_title"" },
        { ""id"": ""ic_vertical_align_bottom"" },
        { ""id"": ""ic_vertical_align_center"" },
        { ""id"": ""ic_vertical_align_top"" },
        { ""id"": ""ic_wrap_text"" }
      ],
      ""name"": ""editor""
    },
    {
      ""icons"": [
        { ""id"": ""ic_attachment"" },
        { ""id"": ""ic_cloud"" },
        { ""id"": ""ic_cloud_circle"" },
        { ""id"": ""ic_cloud_done"" },
        { ""id"": ""ic_cloud_download"" },
        { ""id"": ""ic_cloud_off"" },
        { ""id"": ""ic_cloud_queue"" },
        { ""id"": ""ic_cloud_upload"" },
        { ""id"": ""ic_create_new_folder"" },
        { ""id"": ""ic_folder"" },
        { ""id"": ""ic_folder_open"" },
        { ""id"": ""ic_folder_shared"" }
      ],
      ""name"": ""file""
    },
    {
      ""icons"": [
        { ""id"": ""ic_cast"" },
        { ""id"": ""ic_cast_connected"" },
        {
          ""imageUrls"": {
            ""twotone"": ""twotone-cast_for_education-24px.svg"",
            ""sharp"": ""sharp-cast_for_education-24px.svg"",
            ""outline"": ""outline-cast_for_education-24px.svg"",
            ""round"": ""round-cast_for_education-24px.svg"",
            ""baseline"": ""baseline-cast_for_education-48px.svg""
          },
          ""id"": ""ic_cast_for_education""
        },
        { ""id"": ""ic_computer"" },
        { ""id"": ""ic_desktop_mac"" },
        { ""id"": ""ic_desktop_windows"" },
        { ""id"": ""ic_developer_board"" },
        { ""id"": ""ic_device_hub"" },
        { ""id"": ""ic_device_unknown"" },
        { ""id"": ""ic_devices_other"" },
        { ""id"": ""ic_dock"" },
        { ""id"": ""ic_gamepad"" },
        { ""id"": ""ic_headset"" },
        { ""id"": ""ic_headset_mic"" },
        { ""id"": ""ic_keyboard"" },
        { ""id"": ""ic_keyboard_arrow_down"" },
        { ""id"": ""ic_keyboard_arrow_left"" },
        { ""id"": ""ic_keyboard_arrow_right"" },
        { ""id"": ""ic_keyboard_arrow_up"" },
        { ""id"": ""ic_keyboard_backspace"" },
        { ""id"": ""ic_keyboard_capslock"" },
        { ""id"": ""ic_keyboard_hide"" },
        { ""id"": ""ic_keyboard_return"" },
        { ""id"": ""ic_keyboard_tab"" },
        { ""id"": ""ic_keyboard_voice"" },
        { ""id"": ""ic_laptop"" },
        { ""id"": ""ic_laptop_chromebook"" },
        { ""id"": ""ic_laptop_mac"" },
        { ""id"": ""ic_laptop_windows"" },
        { ""id"": ""ic_memory"" },
        { ""id"": ""ic_mouse"" },
        { ""id"": ""ic_phone_android"" },
        { ""id"": ""ic_phone_iphone"" },
        { ""id"": ""ic_phonelink"" },
        { ""id"": ""ic_phonelink_off"" },
        { ""id"": ""ic_power_input"" },
        { ""id"": ""ic_router"" },
        { ""id"": ""ic_scanner"" },
        { ""id"": ""ic_security"" },
        { ""id"": ""ic_sim_card"" },
        { ""id"": ""ic_smartphone"" },
        { ""id"": ""ic_speaker"" },
        { ""id"": ""ic_speaker_group"" },
        { ""id"": ""ic_tablet"" },
        { ""id"": ""ic_tablet_android"" },
        { ""id"": ""ic_tablet_mac"" },
        { ""id"": ""ic_toys"" },
        { ""id"": ""ic_tv"" },
        { ""id"": ""ic_videogame_asset"" },
        { ""id"": ""ic_watch"" }
      ],
      ""name"": ""hardware""
    },
    {
      ""icons"": [
        { ""id"": ""ic_add_a_photo"" },
        { ""id"": ""ic_add_photo_alternate"" },
        { ""id"": ""ic_add_to_photos"" },
        { ""id"": ""ic_adjust"" },
        { ""id"": ""ic_assistant"" },
        { ""id"": ""ic_assistant_photo"" },
        { ""id"": ""ic_audiotrack"" },
        { ""id"": ""ic_blur_circular"" },
        { ""id"": ""ic_blur_linear"" },
        { ""id"": ""ic_blur_off"" },
        { ""id"": ""ic_blur_on"" },
        { ""id"": ""ic_brightness_1"" },
        { ""id"": ""ic_brightness_2"" },
        { ""id"": ""ic_brightness_3"" },
        { ""id"": ""ic_brightness_4"" },
        { ""id"": ""ic_brightness_5"" },
        { ""id"": ""ic_brightness_6"" },
        { ""id"": ""ic_brightness_7"" },
        { ""id"": ""ic_broken_image"" },
        { ""id"": ""ic_brush"" },
        { ""id"": ""ic_burst_mode"" },
        { ""id"": ""ic_camera"" },
        { ""id"": ""ic_camera_alt"" },
        { ""id"": ""ic_camera_front"" },
        { ""id"": ""ic_camera_rear"" },
        { ""id"": ""ic_camera_roll"" },
        { ""id"": ""ic_center_focus_strong"" },
        { ""id"": ""ic_center_focus_weak"" },
        { ""id"": ""ic_collections"" },
        { ""id"": ""ic_collections_bookmark"" },
        { ""id"": ""ic_color_lens"" },
        { ""id"": ""ic_colorize"" },
        { ""id"": ""ic_compare"" },
        { ""id"": ""ic_control_point"" },
        { ""id"": ""ic_control_point_duplicate"" },
        { ""id"": ""ic_crop"" },
        { ""id"": ""ic_crop_16_9"" },
        { ""id"": ""ic_crop_3_2"" },
        { ""id"": ""ic_crop_5_4"" },
        { ""id"": ""ic_crop_7_5"" },
        { ""id"": ""ic_crop_din"" },
        { ""id"": ""ic_crop_free"" },
        { ""id"": ""ic_crop_landscape"" },
        { ""id"": ""ic_crop_original"" },
        { ""id"": ""ic_crop_portrait"" },
        { ""id"": ""ic_crop_rotate"" },
        { ""id"": ""ic_crop_square"" },
        { ""id"": ""ic_dehaze"" },
        { ""id"": ""ic_details"" },
        { ""id"": ""ic_edit"" },
        { ""id"": ""ic_exposure"" },
        { ""id"": ""ic_exposure_neg_1"" },
        { ""id"": ""ic_exposure_neg_2"" },
        { ""id"": ""ic_exposure_plus_1"" },
        { ""id"": ""ic_exposure_plus_2"" },
        { ""id"": ""ic_exposure_zero"" },
        { ""id"": ""ic_filter"" },
        { ""id"": ""ic_filter_1"" },
        { ""id"": ""ic_filter_2"" },
        { ""id"": ""ic_filter_3"" },
        { ""id"": ""ic_filter_4"" },
        { ""id"": ""ic_filter_5"" },
        { ""id"": ""ic_filter_6"" },
        { ""id"": ""ic_filter_7"" },
        { ""id"": ""ic_filter_8"" },
        { ""id"": ""ic_filter_9"" },
        { ""id"": ""ic_filter_9_plus"" },
        { ""id"": ""ic_filter_b_and_w"" },
        { ""id"": ""ic_filter_center_focus"" },
        { ""id"": ""ic_filter_drama"" },
        { ""id"": ""ic_filter_frames"" },
        { ""id"": ""ic_filter_hdr"" },
        { ""id"": ""ic_filter_none"" },
        { ""id"": ""ic_filter_tilt_shift"" },
        { ""id"": ""ic_filter_vintage"" },
        { ""id"": ""ic_flare"" },
        { ""id"": ""ic_flash_auto"" },
        { ""id"": ""ic_flash_off"" },
        { ""id"": ""ic_flash_on"" },
        { ""id"": ""ic_flip"" },
        { ""id"": ""ic_gradient"" },
        { ""id"": ""ic_grain"" },
        { ""id"": ""ic_grid_off"" },
        { ""id"": ""ic_grid_on"" },
        { ""id"": ""ic_hdr_off"" },
        { ""id"": ""ic_hdr_on"" },
        { ""id"": ""ic_hdr_strong"" },
        { ""id"": ""ic_hdr_weak"" },
        { ""id"": ""ic_healing"" },
        { ""id"": ""ic_image"" },
        { ""id"": ""ic_image_aspect_ratio"" },
        { ""id"": ""ic_image_search"" },
        { ""id"": ""ic_iso"" },
        { ""id"": ""ic_landscape"" },
        { ""id"": ""ic_leak_add"" },
        { ""id"": ""ic_leak_remove"" },
        { ""id"": ""ic_lens"" },
        { ""id"": ""ic_linked_camera"" },
        { ""id"": ""ic_looks"" },
        { ""id"": ""ic_looks_3"" },
        { ""id"": ""ic_looks_4"" },
        { ""id"": ""ic_looks_5"" },
        { ""id"": ""ic_looks_6"" },
        { ""id"": ""ic_looks_one"" },
        { ""id"": ""ic_looks_two"" },
        { ""id"": ""ic_loupe"" },
        { ""id"": ""ic_monochrome_photos"" },
        { ""id"": ""ic_movie_creation"" },
        { ""id"": ""ic_movie_filter"" },
        { ""id"": ""ic_music_note"" },
        { ""id"": ""ic_music_off"" },
        { ""id"": ""ic_nature"" },
        { ""id"": ""ic_nature_people"" },
        { ""id"": ""ic_navigate_before"" },
        { ""id"": ""ic_navigate_next"" },
        { ""id"": ""ic_palette"" },
        { ""id"": ""ic_panorama"" },
        { ""id"": ""ic_panorama_fish_eye"" },
        { ""id"": ""ic_panorama_horizontal"" },
        { ""id"": ""ic_panorama_vertical"" },
        { ""id"": ""ic_panorama_wide_angle"" },
        { ""id"": ""ic_photo"" },
        { ""id"": ""ic_photo_album"" },
        { ""id"": ""ic_photo_camera"" },
        { ""id"": ""ic_photo_filter"" },
        { ""id"": ""ic_photo_library"" },
        { ""id"": ""ic_photo_size_select_actual"" },
        { ""id"": ""ic_photo_size_select_large"" },
        { ""id"": ""ic_photo_size_select_small"" },
        { ""id"": ""ic_picture_as_pdf"" },
        { ""id"": ""ic_portrait"" },
        { ""id"": ""ic_remove_red_eye"" },
        { ""id"": ""ic_rotate_90_degrees_ccw"" },
        { ""id"": ""ic_rotate_left"" },
        { ""id"": ""ic_rotate_right"" },
        { ""id"": ""ic_shutter_speed"" },
        { ""id"": ""ic_slideshow"" },
        { ""id"": ""ic_straighten"" },
        { ""id"": ""ic_style"" },
        { ""id"": ""ic_switch_camera"" },
        { ""id"": ""ic_switch_video"" },
        { ""id"": ""ic_tag_faces"" },
        { ""id"": ""ic_texture"" },
        { ""id"": ""ic_timelapse"" },
        { ""id"": ""ic_timer"" },
        { ""id"": ""ic_timer_10"" },
        { ""id"": ""ic_timer_3"" },
        { ""id"": ""ic_timer_off"" },
        { ""id"": ""ic_tonality"" },
        { ""id"": ""ic_transform"" },
        { ""id"": ""ic_tune"" },
        { ""id"": ""ic_view_comfy"" },
        { ""id"": ""ic_view_compact"" },
        { ""id"": ""ic_vignette"" },
        { ""id"": ""ic_wb_auto"" },
        { ""id"": ""ic_wb_cloudy"" },
        { ""id"": ""ic_wb_incandescent"" },
        { ""id"": ""ic_wb_iridescent"" },
        { ""id"": ""ic_wb_sunny"" }
      ],
      ""name"": ""image""
    },
    {
      ""icons"": [
        { ""id"": ""ic_360"" },
        { ""id"": ""ic_add_location"" },
        { ""id"": ""ic_atm"" },
        { ""id"": ""ic_beenhere"" },
        { ""id"": ""ic_category"" },
        { ""id"": ""ic_compass_calibration"" },
        { ""id"": ""ic_departure_board"" },
        { ""id"": ""ic_directions"" },
        { ""id"": ""ic_directions_bike"" },
        { ""id"": ""ic_directions_boat"" },
        { ""id"": ""ic_directions_bus"" },
        { ""id"": ""ic_directions_car"" },
        { ""id"": ""ic_directions_railway"" },
        { ""id"": ""ic_directions_run"" },
        { ""id"": ""ic_directions_subway"" },
        { ""id"": ""ic_directions_transit"" },
        { ""id"": ""ic_directions_walk"" },
        { ""id"": ""ic_edit_attributes"" },
        { ""id"": ""ic_edit_location"" },
        { ""id"": ""ic_ev_station"" },
        { ""id"": ""ic_fastfood"" },
        { ""id"": ""ic_flight"" },
        { ""id"": ""ic_hotel"" },
        { ""id"": ""ic_layers"" },
        { ""id"": ""ic_layers_clear"" },
        { ""id"": ""ic_local_activity"" },
        { ""id"": ""ic_local_airport"" },
        { ""id"": ""ic_local_atm"" },
        { ""id"": ""ic_local_bar"" },
        { ""id"": ""ic_local_cafe"" },
        { ""id"": ""ic_local_car_wash"" },
        { ""id"": ""ic_local_convenience_store"" },
        { ""id"": ""ic_local_dining"" },
        { ""id"": ""ic_local_drink"" },
        { ""id"": ""ic_local_florist"" },
        { ""id"": ""ic_local_gas_station"" },
        { ""id"": ""ic_local_grocery_store"" },
        { ""id"": ""ic_local_hospital"" },
        { ""id"": ""ic_local_hotel"" },
        { ""id"": ""ic_local_laundry_service"" },
        { ""id"": ""ic_local_library"" },
        { ""id"": ""ic_local_mall"" },
        { ""id"": ""ic_local_movies"" },
        { ""id"": ""ic_local_offer"" },
        { ""id"": ""ic_local_parking"" },
        { ""id"": ""ic_local_pharmacy"" },
        { ""id"": ""ic_local_phone"" },
        { ""id"": ""ic_local_pizza"" },
        { ""id"": ""ic_local_play"" },
        { ""id"": ""ic_local_post_office"" },
        { ""id"": ""ic_local_printshop"" },
        { ""id"": ""ic_local_see"" },
        { ""id"": ""ic_local_shipping"" },
        { ""id"": ""ic_local_taxi"" },
        { ""id"": ""ic_map"" },
        { ""id"": ""ic_money"" },
        { ""id"": ""ic_my_location"" },
        { ""id"": ""ic_navigation"" },
        { ""id"": ""ic_near_me"" },
        { ""id"": ""ic_not_listed_location"" },
        { ""id"": ""ic_person_pin"" },
        { ""id"": ""ic_person_pin_circle"" },
        { ""id"": ""ic_pin_drop"" },
        { ""id"": ""ic_place"" },
        { ""id"": ""ic_rate_review"" },
        { ""id"": ""ic_restaurant"" },
        { ""id"": ""ic_restaurant_menu"" },
        { ""id"": ""ic_satellite"" },
        { ""id"": ""ic_store_mall_directory"" },
        { ""id"": ""ic_streetview"" },
        { ""id"": ""ic_subway"" },
        { ""id"": ""ic_terrain"" },
        { ""id"": ""ic_traffic"" },
        { ""id"": ""ic_train"" },
        { ""id"": ""ic_tram"" },
        { ""id"": ""ic_transfer_within_a_station"" },
        { ""id"": ""ic_transit_enterexit"" },
        { ""id"": ""ic_trip_origin"" },
        { ""id"": ""ic_zoom_out_map"" }
      ],
      ""name"": ""maps""
    },
    {
      ""icons"": [
        { ""id"": ""ic_apps"" },
        { ""id"": ""ic_arrow_back"" },
        { ""id"": ""ic_arrow_back_ios"" },
        { ""id"": ""ic_arrow_downward"" },
        { ""id"": ""ic_arrow_drop_down"" },
        { ""id"": ""ic_arrow_drop_down_circle"" },
        { ""id"": ""ic_arrow_drop_up"" },
        { ""id"": ""ic_arrow_forward"" },
        { ""id"": ""ic_arrow_forward_ios"" },
        { ""id"": ""ic_arrow_left"" },
        { ""id"": ""ic_arrow_right"" },
        { ""id"": ""ic_arrow_upward"" },
        { ""id"": ""ic_cancel"" },
        { ""id"": ""ic_check"" },
        { ""id"": ""ic_chevron_left"" },
        { ""id"": ""ic_chevron_right"" },
        { ""id"": ""ic_close"" },
        { ""id"": ""ic_expand_less"" },
        { ""id"": ""ic_expand_more"" },
        { ""id"": ""ic_first_page"" },
        { ""id"": ""ic_fullscreen"" },
        { ""id"": ""ic_fullscreen_exit"" },
        { ""id"": ""ic_last_page"" },
        { ""id"": ""ic_menu"" },
        { ""id"": ""ic_more_horiz"" },
        { ""id"": ""ic_more_vert"" },
        { ""id"": ""ic_refresh"" },
        { ""id"": ""ic_subdirectory_arrow_left"" },
        { ""id"": ""ic_subdirectory_arrow_right"" },
        { ""id"": ""ic_unfold_less"" },
        { ""id"": ""ic_unfold_more"" }
      ],
      ""name"": ""navigation""
    },
    {
      ""icons"": [
        { ""id"": ""ic_adb"" },
        { ""id"": ""ic_airline_seat_flat"" },
        { ""id"": ""ic_airline_seat_flat_angled"" },
        { ""id"": ""ic_airline_seat_individual_suite"" },
        { ""id"": ""ic_airline_seat_legroom_extra"" },
        { ""id"": ""ic_airline_seat_legroom_normal"" },
        { ""id"": ""ic_airline_seat_legroom_reduced"" },
        { ""id"": ""ic_airline_seat_recline_extra"" },
        { ""id"": ""ic_airline_seat_recline_normal"" },
        { ""id"": ""ic_bluetooth_audio"" },
        { ""id"": ""ic_confirmation_number"" },
        { ""id"": ""ic_disc_full"" },
        { ""id"": ""ic_drive_eta"" },
        { ""id"": ""ic_enhanced_encryption"" },
        { ""id"": ""ic_event_available"" },
        { ""id"": ""ic_event_busy"" },
        { ""id"": ""ic_event_note"" },
        { ""id"": ""ic_folder_special"" },
        { ""id"": ""ic_live_tv"" },
        { ""id"": ""ic_mms"" },
        { ""id"": ""ic_more"" },
        { ""id"": ""ic_network_check"" },
        { ""id"": ""ic_network_locked"" },
        { ""id"": ""ic_no_encryption"" },
        { ""id"": ""ic_ondemand_video"" },
        { ""id"": ""ic_personal_video"" },
        { ""id"": ""ic_phone_bluetooth_speaker"" },
        { ""id"": ""ic_phone_callback"" },
        { ""id"": ""ic_phone_forwarded"" },
        { ""id"": ""ic_phone_in_talk"" },
        { ""id"": ""ic_phone_locked"" },
        { ""id"": ""ic_phone_missed"" },
        { ""id"": ""ic_phone_paused"" },
        { ""id"": ""ic_power"" },
        { ""id"": ""ic_power_off"" },
        { ""id"": ""ic_priority_high"" },
        { ""id"": ""ic_sd_card"" },
        { ""id"": ""ic_sms"" },
        { ""id"": ""ic_sms_failed"" },
        { ""id"": ""ic_sync"" },
        { ""id"": ""ic_sync_disabled"" },
        { ""id"": ""ic_sync_problem"" },
        { ""id"": ""ic_system_update"" },
        { ""id"": ""ic_tap_and_play"" },
        { ""id"": ""ic_time_to_leave"" },
        { ""id"": ""ic_tv_off"" },
        { ""id"": ""ic_vibration"" },
        { ""id"": ""ic_voice_chat"" },
        { ""id"": ""ic_vpn_lock"" },
        { ""id"": ""ic_wc"" },
        { ""id"": ""ic_wifi"" },
        { ""id"": ""ic_wifi_off"" }
      ],
      ""name"": ""notification""
    },
    {
      ""icons"": [
        { ""id"": ""ic_ac_unit"" },
        { ""id"": ""ic_airport_shuttle"" },
        { ""id"": ""ic_all_inclusive"" },
        { ""id"": ""ic_beach_access"" },
        { ""id"": ""ic_business_center"" },
        { ""id"": ""ic_casino"" },
        { ""id"": ""ic_child_care"" },
        { ""id"": ""ic_child_friendly"" },
        { ""id"": ""ic_fitness_center"" },
        { ""id"": ""ic_free_breakfast"" },
        { ""id"": ""ic_golf_course"" },
        { ""id"": ""ic_hot_tub"" },
        { ""id"": ""ic_kitchen"" },
        { ""id"": ""ic_meeting_room"" },
        { ""id"": ""ic_no_meeting_room"" },
        { ""id"": ""ic_pool"" },
        { ""id"": ""ic_room_service"" },
        { ""id"": ""ic_rv_hookup"" },
        { ""id"": ""ic_smoke_free"" },
        { ""id"": ""ic_smoking_rooms"" },
        { ""id"": ""ic_spa"" }
      ],
      ""name"": ""places""
    },
    {
      ""icons"": [
        { ""id"": ""ic_cake"" },
        {
          ""imageUrls"": {
            ""twotone"": ""twotone-domain-24px.svg"",
            ""sharp"": ""sharp-domain-24px.svg"",
            ""outline"": ""outline-domain-24px.svg"",
            ""round"": ""round-domain-24px.svg"",
            ""baseline"": ""baseline-domain-48px.svg""
          },
          ""id"": ""ic_domain""
        },
        { ""id"": ""ic_group"" },
        { ""id"": ""ic_group_add"" },
        { ""id"": ""ic_location_city"" },
        { ""id"": ""ic_mood"" },
        { ""id"": ""ic_mood_bad"" },
        { ""id"": ""ic_notifications"" },
        { ""id"": ""ic_notifications_active"" },
        { ""id"": ""ic_notifications_none"" },
        { ""id"": ""ic_notifications_off"" },
        { ""id"": ""ic_notifications_paused"" },
        { ""id"": ""ic_pages"" },
        { ""id"": ""ic_party_mode"" },
        { ""id"": ""ic_people"" },
        { ""id"": ""ic_people_outline"" },
        { ""id"": ""ic_person"" },
        { ""id"": ""ic_person_add"" },
        { ""id"": ""ic_person_outline"" },
        { ""id"": ""ic_plus_one"" },
        { ""id"": ""ic_poll"" },
        { ""id"": ""ic_public"" },
        { ""id"": ""ic_school"" },
        { ""id"": ""ic_sentiment_dissatisfied"" },
        { ""id"": ""ic_sentiment_satisfied"" },
        { ""id"": ""ic_sentiment_very_dissatisfied"" },
        { ""id"": ""ic_sentiment_very_satisfied"" },
        { ""id"": ""ic_share"" },
        { ""id"": ""ic_thumb_down_alt"" },
        { ""id"": ""ic_thumb_up_alt"" },
        { ""id"": ""ic_whatshot"" }
      ],
      ""name"": ""social""
    },
    {
      ""icons"": [
        { ""id"": ""ic_check_box"" },
        { ""id"": ""ic_check_box_outline_blank"" },
        { ""id"": ""ic_indeterminate_check_box"" },
        { ""id"": ""ic_radio_button_checked"" },
        { ""id"": ""ic_radio_button_unchecked"" },
        { ""id"": ""ic_star"" },
        { ""id"": ""ic_star_border"" },
        { ""id"": ""ic_star_half"" },
        { ""id"": ""ic_toggle_off"" },
        { ""id"": ""ic_toggle_on"" }
      ],
      ""name"": ""toggle""
    }
  ]
}
            ";
        }
    }
}
